const map = {
  button: {
    'if': {type: 'condition', value: 'if', label: 'if'},
    'then': {type: 'condition', value: 'then', label: 'then'},
    'else': {type: 'condition', value: 'else', label: 'else'},
    'and': {type: 'condition', value: 'and', label: 'and'},
    'or': {type: 'condition', value: 'or', label: 'or'},
    'not': {type: 'condition', value: 'not', label: 'not'},
    '(': {type: 'operator', value: '(', label: '('},
    ')': {type: 'operator', value: ')', label: ')'},
    '+': {type: 'operator', value: '+', label: '+'},
    '-': {type: 'operator', value: '-', label: '-'},
    '*': {type: 'operator', value: '*', label: '*'},
    '/': {type: 'operator', value: '/', label: '/'},
    '.': {type: 'operator', value: '.', label: '.'},
    '=': {type: 'operator', value: '=', label: '='},
    '<': {type: 'operator', value: '<', label: '<'},
    '>': {type: 'operator', value: '>', label: '>'},
    '!=': {type: 'operator', value: '!=', label: '!='},
    '≤': {type: 'operator', value: '≤', label: '≤'},
    '≥': {type: 'operator', value: '≥', label: '≥'},
    'enter': {type: 'editor', value: '\n', label: '\n'},
    'ce': {type: 'editor', value: 'ce', label: 'ce'},
    '1': {type: 'number', value: '1', label: '1'},
    '2': {type: 'number', value: '2', label: '2'},
    '3': {type: 'number', value: '3', label: '3'},
    '4': {type: 'number', value: '4', label: '4'},
    '5': {type: 'number', value: '5', label: '5'},
    '6': {type: 'number', value: '6', label: '6'},
    '7': {type: 'number', value: '7', label: '7'},
    '8': {type: 'number', value: '8', label: '8'},
    '9': {type: 'number', value: '9', label: '9'},
    '0': {type: 'number', value: '0', label: '0'}
  },
  tree: {}
}
export default map
